#postgres:
#  image: postgres:9.4.5
#  environment:
#    POSTGRES_USER: pasta
#    POSTGRES_PASSWORD: yourpassword
#  ports:
#    - '5432:5432'
#  volumes:
#    - pasta-postgres:/var/lib/postgresql/data

#redis:
#  image: redis:3.0.5
#  ports:
#    - '6379:6379'
#  volumes:
#    - pasta-redis:/var/lib/redis/data

pasta:
  build: .
#  links:
#    - postgres
#    - redis
  volumes:
    - .:/pasta
  ports:
    - '8000:8000'
  env_file:
    - .pasta.env

#sidekiq:
#  build: .
#  command: bundle exec sidekiq -C config/sidekiq.yml
##  links:
##    - postgres
##    - redis
#  volumes:
#    - .:/pasta
#  env_file:
#    - .pasta.env
