# https://semaphoreci.com/community/tutorials/dockerizing-a-ruby-on-rails-application
---

default: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

