# https://semaphoreci.com/community/tutorials/dockerizing-a-ruby-on-rails-application
---

development: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

